/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspecaoIdVeiculoRouteImport } from './routes/inspecao.$id.veiculo'
import { Route as InspecaoIdTipoVeiculoRouteImport } from './routes/inspecao.$id.tipo-veiculo'
import { Route as InspecaoIdResumoRouteImport } from './routes/inspecao.$id.resumo'
import { Route as InspecaoIdInteligenteRouteImport } from './routes/inspecao.$id.inteligente'
import { Route as InspecaoIdChecklistRouteImport } from './routes/inspecao.$id.checklist'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdVeiculoRoute = InspecaoIdVeiculoRouteImport.update({
  id: '/inspecao/$id/veiculo',
  path: '/inspecao/$id/veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdTipoVeiculoRoute = InspecaoIdTipoVeiculoRouteImport.update({
  id: '/inspecao/$id/tipo-veiculo',
  path: '/inspecao/$id/tipo-veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdResumoRoute = InspecaoIdResumoRouteImport.update({
  id: '/inspecao/$id/resumo',
  path: '/inspecao/$id/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdInteligenteRoute = InspecaoIdInteligenteRouteImport.update({
  id: '/inspecao/$id/inteligente',
  path: '/inspecao/$id/inteligente',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdChecklistRoute = InspecaoIdChecklistRouteImport.update({
  id: '/inspecao/$id/checklist',
  path: '/inspecao/$id/checklist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  id:
    | '__root__'
    | '/'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InspecaoIdChecklistRoute: typeof InspecaoIdChecklistRoute
  InspecaoIdInteligenteRoute: typeof InspecaoIdInteligenteRoute
  InspecaoIdResumoRoute: typeof InspecaoIdResumoRoute
  InspecaoIdTipoVeiculoRoute: typeof InspecaoIdTipoVeiculoRoute
  InspecaoIdVeiculoRoute: typeof InspecaoIdVeiculoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/veiculo': {
      id: '/inspecao/$id/veiculo'
      path: '/inspecao/$id/veiculo'
      fullPath: '/inspecao/$id/veiculo'
      preLoaderRoute: typeof InspecaoIdVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/tipo-veiculo': {
      id: '/inspecao/$id/tipo-veiculo'
      path: '/inspecao/$id/tipo-veiculo'
      fullPath: '/inspecao/$id/tipo-veiculo'
      preLoaderRoute: typeof InspecaoIdTipoVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/resumo': {
      id: '/inspecao/$id/resumo'
      path: '/inspecao/$id/resumo'
      fullPath: '/inspecao/$id/resumo'
      preLoaderRoute: typeof InspecaoIdResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/inteligente': {
      id: '/inspecao/$id/inteligente'
      path: '/inspecao/$id/inteligente'
      fullPath: '/inspecao/$id/inteligente'
      preLoaderRoute: typeof InspecaoIdInteligenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/checklist': {
      id: '/inspecao/$id/checklist'
      path: '/inspecao/$id/checklist'
      fullPath: '/inspecao/$id/checklist'
      preLoaderRoute: typeof InspecaoIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InspecaoIdChecklistRoute: InspecaoIdChecklistRoute,
  InspecaoIdInteligenteRoute: InspecaoIdInteligenteRoute,
  InspecaoIdResumoRoute: InspecaoIdResumoRoute,
  InspecaoIdTipoVeiculoRoute: InspecaoIdTipoVeiculoRoute,
  InspecaoIdVeiculoRoute: InspecaoIdVeiculoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
