/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as ConsultaPlacaRouteImport } from './routes/consulta-placa'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as InspecaoIdVeiculoRouteImport } from './routes/inspecao.$id.veiculo'
import { Route as InspecaoIdTipoVeiculoRouteImport } from './routes/inspecao.$id.tipo-veiculo'
import { Route as InspecaoIdResumoRouteImport } from './routes/inspecao.$id.resumo'
import { Route as InspecaoIdInteligenteRouteImport } from './routes/inspecao.$id.inteligente'
import { Route as InspecaoIdChecklistRouteImport } from './routes/inspecao.$id.checklist'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaPlacaRoute = ConsultaPlacaRouteImport.update({
  id: '/consulta-placa',
  path: '/consulta-placa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const InspecaoIdVeiculoRoute = InspecaoIdVeiculoRouteImport.update({
  id: '/inspecao/$id/veiculo',
  path: '/inspecao/$id/veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdTipoVeiculoRoute = InspecaoIdTipoVeiculoRouteImport.update({
  id: '/inspecao/$id/tipo-veiculo',
  path: '/inspecao/$id/tipo-veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdResumoRoute = InspecaoIdResumoRouteImport.update({
  id: '/inspecao/$id/resumo',
  path: '/inspecao/$id/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdInteligenteRoute = InspecaoIdInteligenteRouteImport.update({
  id: '/inspecao/$id/inteligente',
  path: '/inspecao/$id/inteligente',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIdChecklistRoute = InspecaoIdChecklistRouteImport.update({
  id: '/inspecao/$id/checklist',
  path: '/inspecao/$id/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-placa': typeof ConsultaPlacaRoute
  '/estatisticas': typeof EstatisticasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-placa': typeof ConsultaPlacaRoute
  '/estatisticas': typeof EstatisticasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-placa': typeof ConsultaPlacaRoute
  '/estatisticas': typeof EstatisticasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/inspecao/$id/checklist': typeof InspecaoIdChecklistRoute
  '/inspecao/$id/inteligente': typeof InspecaoIdInteligenteRoute
  '/inspecao/$id/resumo': typeof InspecaoIdResumoRoute
  '/inspecao/$id/tipo-veiculo': typeof InspecaoIdTipoVeiculoRoute
  '/inspecao/$id/veiculo': typeof InspecaoIdVeiculoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/consulta-placa'
    | '/estatisticas'
    | '/historico'
    | '/login'
    | '/manual'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/consulta-placa'
    | '/estatisticas'
    | '/historico'
    | '/login'
    | '/manual'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/consulta-placa'
    | '/estatisticas'
    | '/historico'
    | '/login'
    | '/manual'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/inspecao/$id/checklist'
    | '/inspecao/$id/inteligente'
    | '/inspecao/$id/resumo'
    | '/inspecao/$id/tipo-veiculo'
    | '/inspecao/$id/veiculo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultaPlacaRoute: typeof ConsultaPlacaRoute
  EstatisticasRoute: typeof EstatisticasRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  InspecaoIdChecklistRoute: typeof InspecaoIdChecklistRoute
  InspecaoIdInteligenteRoute: typeof InspecaoIdInteligenteRoute
  InspecaoIdResumoRoute: typeof InspecaoIdResumoRoute
  InspecaoIdTipoVeiculoRoute: typeof InspecaoIdTipoVeiculoRoute
  InspecaoIdVeiculoRoute: typeof InspecaoIdVeiculoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-placa': {
      id: '/consulta-placa'
      path: '/consulta-placa'
      fullPath: '/consulta-placa'
      preLoaderRoute: typeof ConsultaPlacaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/veiculo': {
      id: '/inspecao/$id/veiculo'
      path: '/inspecao/$id/veiculo'
      fullPath: '/inspecao/$id/veiculo'
      preLoaderRoute: typeof InspecaoIdVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/tipo-veiculo': {
      id: '/inspecao/$id/tipo-veiculo'
      path: '/inspecao/$id/tipo-veiculo'
      fullPath: '/inspecao/$id/tipo-veiculo'
      preLoaderRoute: typeof InspecaoIdTipoVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/resumo': {
      id: '/inspecao/$id/resumo'
      path: '/inspecao/$id/resumo'
      fullPath: '/inspecao/$id/resumo'
      preLoaderRoute: typeof InspecaoIdResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/inteligente': {
      id: '/inspecao/$id/inteligente'
      path: '/inspecao/$id/inteligente'
      fullPath: '/inspecao/$id/inteligente'
      preLoaderRoute: typeof InspecaoIdInteligenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/$id/checklist': {
      id: '/inspecao/$id/checklist'
      path: '/inspecao/$id/checklist'
      fullPath: '/inspecao/$id/checklist'
      preLoaderRoute: typeof InspecaoIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultaPlacaRoute: ConsultaPlacaRoute,
  EstatisticasRoute: EstatisticasRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  InspecaoIdChecklistRoute: InspecaoIdChecklistRoute,
  InspecaoIdInteligenteRoute: InspecaoIdInteligenteRoute,
  InspecaoIdResumoRoute: InspecaoIdResumoRoute,
  InspecaoIdTipoVeiculoRoute: InspecaoIdTipoVeiculoRoute,
  InspecaoIdVeiculoRoute: InspecaoIdVeiculoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
